import React from 'react'
import './Home.css'

const Home = () => {
  return (
    <div className='home-bg'>
       <h1 className='home-text'>Welcome to the Home page</h1>
       <p className='home-small-text'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cum aliquid quibusdam asperiores ipsam nostrum, sint ipsa quod commodi excepturi similique.</p>
       <p className='home-small-text'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam repudiandae ipsa excepturi dolorum doloribus, laudantium odio? Laborum vero nisi enim doloremque deserunt laboriosam. Soluta fuga cum iste distinctio error a dignissimos, quisquam harum expedita corporis non deserunt quas voluptatibus voluptates. Tempore eos labore fugit aperiam praesentium molestiae, minus est delectus dicta distinctio quod corrupti, sit quos beatae ab consectetur dolores necessitatibus doloribus. Quas quibusdam doloremque pariatur ex quo modi porro deleniti earum at non, saepe exercitationem neque rem veniam autem quasi sequi accusamus perferendis. Sit sapiente hic sequi illo, a nulla praesentium, id aspernatur mollitia enim suscipit adipisci voluptates maiores.</p>
       <p className='home-small-text'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad nulla nam quidem beatae, possimus, quis sapiente dolores, similique provident natus odio voluptate. Sapiente aliquam vel iste fuga vitae repellat laboriosam..</p>
       <p className='home-small-text'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam repudiandae ipsa excepturi dolorum doloribus, laudantium odio? Laborum vero nisi enim doloremque deserunt laboriosam. Soluta fuga cum iste distinctio error a dignissimos, quisquam harum expedita corporis non deserunt quas voluptatibus voluptates. Tempore eos labore fugit aperiam praesentium molestiae, minus est delectus dicta distinctio quod corrupti, sit quos beatae ab consectetur dolores necessitatibus doloribus. Quas quibusdam doloremque pariatur ex quo modi porro deleniti earum at non, saepe exercitationem neque rem veniam autem quasi sequi accusamus perferendis. Sit sapiente hic sequi illo, a nulla praesentium, id aspernatur mollitia enim suscipit adipisci voluptates maiores.</p>
       <p className='home-small-text'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam repudiandae ipsa excepturi dolorum doloribus, laudantium odio? Laborum vero nisi enim doloremque deserunt laboriosam. Soluta fuga cum iste distinctio error a dignissimos, quisquam harum expedita corporis non deserunt quas voluptatibus voluptates. Tempore eos labore fugit aperiam praesentium molestiae, minus est delectus dicta distinctio quod corrupti, sit quos beatae ab consectetur dolores necessitatibus doloribus. Quas quibusdam doloremque pariatur ex quo modi porro deleniti earum at non, saepe exercitationem neque rem veniam autem quasi sequi accusamus perferendis. Sit sapiente hic sequi illo, a nulla praesentium, id aspernatur mollitia enim suscipit adipisci voluptates maiores.</p>
       <p className='home-small-text'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam repudiandae ipsa excepturi dolorum doloribus, laudantium odio? Laborum vero nisi enim doloremque deserunt laboriosam. Soluta fuga cum iste distinctio error a dignissimos, quisquam harum expedita corporis non deserunt quas voluptatibus voluptates. Tempore eos labore fugit aperiam praesentium molestiae, minus est delectus dicta distinctio quod corrupti, sit quos beatae ab consectetur dolores necessitatibus doloribus. Quas quibusdam doloremque pariatur ex quo modi porro deleniti earum at non, saepe exercitationem neque rem veniam autem quasi sequi accusamus perferendis. Sit sapiente hic sequi illo, a nulla praesentium, id aspernatur mollitia enim suscipit adipisci voluptates maiores.</p>
    </div>
  )
}

export default Home